name: Deploy App

on:
  workflow_dispatch:  # Ejecutarlo manualmente desde GitHub

jobs:
  deploy:
    runs-on: NSUAZO  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull image from GHCR
      shell: bash
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}/api:dev
        IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
        docker pull $IMAGE_NAME

    - name: Create .env file from GitHub Secrets
      shell: bash
      run: |
        echo "DB_SERVER=${{ secrets.DB_SERVER }}" > .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_KEY=${{ secrets.JWT_KEY }}" >> .env

    - name: Run container with .env
      shell: bash
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}/api:dev
        IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
        docker run --env-file .env -d -p 9090:8080 --name api_container $IMAGE_NAME
